spring:
  application:
    name: Ecommerce

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update   # Options: validate | update | create | create-drop
    show-sql: true       # Enables SQL logging
    properties:
      hibernate:
        format_sql: true

  jackson:
    default-property-inclusion: non_empty
    property-naming-strategy: SNAKE_CASE

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 178106561167-vegkgpul728ucfg2v374fbk50ove9p14.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email

server:
  port: 8019
