spring:
  application:
    name: Ecommerce

#  datasource:
#    url: jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&serverTimezone=UTC
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update   # Options: validate | update | create | create-drop
#    show-sql: true       # Enables SQL logging
#    properties:
#      hibernate:
#        format_sql: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  login:
    redirect-uri: ${GOOGLE_LOGIN_REDIRECT_URI}

  jackson:
    default-property-inclusion: non_empty
    property-naming-strategy: SNAKE_CASE

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

server:
  port: 8019

  servlet:
    session:
      cookie:
        same-site: None
        secure: true